# .github/workflows/TagBot.yml
name: TagBot
on:
  push:
    tags:
      - 'v*'       

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}